[package]
name = "iocsh"
version = "0.1.0"
authors = ["Bruno Martins <bm2787@columbia.edu>"]
edition = "2018"

[lib]
name = "iocsh"
crate-type = ["cdylib", "staticlib"]

[dependencies]
libc = "0.2"
lazy_static = "1.3.0"
rustyline = "3.0.0"
regex = "1.1.6"
